export const FILES_CONTENT: Record<string, string[]> = {
  "main.c": [
    "#include <stdio.h>",
    '#include "portfolio.h"',
    "",
    "int main(void)",
    "{",
    "        struct portfolio wolf;",
    "",
    '        wolf = portfolio_init("Szymon Wilczek");',
    "        portfolio_render(&wolf);",
    "        portfolio_free(&wolf);",
    "",
    "        return 0;",
    "}",
  ],
  "portfolio.h": [
    "#ifndef PORTFOLIO_H",
    "#define PORTFOLIO_H",
    "",
    "struct portfolio {",
    "        char *name;",
    "        int year;",
    "        int semester;",
    "};",
    "",
    "struct portfolio portfolio_init(const char *name);",
    "void portfolio_render(const struct portfolio *p);",
    "void portfolio_free(struct portfolio *p);",
    "",
    "#endif /* PORTFOLIO_H */",
  ],
  "portfolio.c": [
    '#include "portfolio.h"',
    "#include <stdlib.h>",
    "#include <string.h>",
    "",
    "struct portfolio portfolio_init(const char *name)",
    "{",
    "        struct portfolio p;",
    "",
    "        p.name = strdup(name);",
    "        p.year = 2026;",
    "        p.semester = 6;",
    "",
    "        return p;",
    "}",
    "",
    "void portfolio_render(const struct portfolio *p)",
    "{",
    "        /* FIXME: drop this dead legacy branch */",
    "        if (p == NULL && p != NULL) {",
    "                legacy_render_deprecated(p);",
    "                return;",
    "        }",
    "",
    '        printf("%s :: sem %d\\n", p->name, p->semester);',
    "}",
  ],
};
